/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cloud.dataflow.city.entity;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventStatisticSubject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1649394869304515110L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventStatisticSubject\",\"namespace\":\"cloud.dataflow.city.entity\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"activities\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EventStatisticSubjectActivities\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"past7daysCount\",\"type\":\"int\"},{\"name\":\"past7daysUniqueCount\",\"type\":\"int\"},{\"name\":\"past30daysCount\",\"type\":\"int\"},{\"name\":\"past30daysUniqueCount\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventStatisticSubject> ENCODER =
      new BinaryMessageEncoder<EventStatisticSubject>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventStatisticSubject> DECODER =
      new BinaryMessageDecoder<EventStatisticSubject>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EventStatisticSubject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EventStatisticSubject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventStatisticSubject>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EventStatisticSubject to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EventStatisticSubject from a ByteBuffer. */
  public static EventStatisticSubject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> activities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventStatisticSubject() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param type The new value for type
   * @param activities The new value for activities
   */
  public EventStatisticSubject(java.lang.Long id, java.lang.CharSequence type, java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> activities) {
    this.id = id;
    this.type = type;
    this.activities = activities;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return type;
    case 2: return activities;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: activities = (java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'activities' field.
   * @return The value of the 'activities' field.
   */
  public java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> getActivities() {
    return activities;
  }

  /**
   * Sets the value of the 'activities' field.
   * @param value the value to set.
   */
  public void setActivities(java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> value) {
    this.activities = value;
  }

  /**
   * Creates a new EventStatisticSubject RecordBuilder.
   * @return A new EventStatisticSubject RecordBuilder
   */
  public static cloud.dataflow.city.entity.EventStatisticSubject.Builder newBuilder() {
    return new cloud.dataflow.city.entity.EventStatisticSubject.Builder();
  }

  /**
   * Creates a new EventStatisticSubject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventStatisticSubject RecordBuilder
   */
  public static cloud.dataflow.city.entity.EventStatisticSubject.Builder newBuilder(cloud.dataflow.city.entity.EventStatisticSubject.Builder other) {
    return new cloud.dataflow.city.entity.EventStatisticSubject.Builder(other);
  }

  /**
   * Creates a new EventStatisticSubject RecordBuilder by copying an existing EventStatisticSubject instance.
   * @param other The existing instance to copy.
   * @return A new EventStatisticSubject RecordBuilder
   */
  public static cloud.dataflow.city.entity.EventStatisticSubject.Builder newBuilder(cloud.dataflow.city.entity.EventStatisticSubject other) {
    return new cloud.dataflow.city.entity.EventStatisticSubject.Builder(other);
  }

  /**
   * RecordBuilder for EventStatisticSubject instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventStatisticSubject>
    implements org.apache.avro.data.RecordBuilder<EventStatisticSubject> {

    private long id;
    private java.lang.CharSequence type;
    private java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> activities;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cloud.dataflow.city.entity.EventStatisticSubject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.activities)) {
        this.activities = data().deepCopy(fields()[2].schema(), other.activities);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EventStatisticSubject instance
     * @param other The existing instance to copy.
     */
    private Builder(cloud.dataflow.city.entity.EventStatisticSubject other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.activities)) {
        this.activities = data().deepCopy(fields()[2].schema(), other.activities);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public cloud.dataflow.city.entity.EventStatisticSubject.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public cloud.dataflow.city.entity.EventStatisticSubject.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public cloud.dataflow.city.entity.EventStatisticSubject.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public cloud.dataflow.city.entity.EventStatisticSubject.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'activities' field.
      * @return The value.
      */
    public java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> getActivities() {
      return activities;
    }

    /**
      * Sets the value of the 'activities' field.
      * @param value The value of 'activities'.
      * @return This builder.
      */
    public cloud.dataflow.city.entity.EventStatisticSubject.Builder setActivities(java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities> value) {
      validate(fields()[2], value);
      this.activities = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'activities' field has been set.
      * @return True if the 'activities' field has been set, false otherwise.
      */
    public boolean hasActivities() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'activities' field.
      * @return This builder.
      */
    public cloud.dataflow.city.entity.EventStatisticSubject.Builder clearActivities() {
      activities = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventStatisticSubject build() {
      try {
        EventStatisticSubject record = new EventStatisticSubject();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.activities = fieldSetFlags()[2] ? this.activities : (java.util.List<cloud.dataflow.city.entity.EventStatisticSubjectActivities>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventStatisticSubject>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventStatisticSubject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventStatisticSubject>
    READER$ = (org.apache.avro.io.DatumReader<EventStatisticSubject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
